const quiz = [

{ko:"안녕",jp:"こんにちは",category:"greeting",level:1},
{ko:"고마워",jp:"ありがとう",category:"greeting",level:1},
{ko:"미안해",jp:"ごめん",category:"greeting",level:1},
{ko:"잘 자",jp:"おやすみ",category:"greeting",level:1},
{ko:"괜찮아",jp:"大丈夫",category:"greeting",level:1},

{ko:"친구",jp:"友達",category:"people",level:1},
{ko:"학생",jp:"学生",category:"people",level:1},
{ko:"선생님",jp:"先生",category:"people",level:1},
{ko:"엄마",jp:"お母さん",category:"people",level:1},
{ko:"아빠",jp:"お父さん",category:"people",level:1},
{ko:"형",jp:"兄",category:"people",level:1},
{ko:"누나",jp:"姉",category:"people",level:1},

{ko:"학교",jp:"学校",category:"school",level:1},
{ko:"책",jp:"本",category:"school",level:1},
{ko:"공부",jp:"勉強",category:"school",level:1},
{ko:"시험",jp:"試験",category:"school",level:1},
{ko:"교실",jp:"教室",category:"school",level:1},

{ko:"물",jp:"水",category:"food",level:1},
{ko:"커피",jp:"コーヒー",category:"food",level:1},
{ko:"밥",jp:"ご飯",category:"food",level:1},
{ko:"사과",jp:"りんご",category:"food",level:1},
{ko:"우유",jp:"牛乳",category:"food",level:1},
{ko:"빵",jp:"パン",category:"food",level:1},

{ko:"집",jp:"家",category:"daily",level:1},
{ko:"전화",jp:"電話",category:"daily",level:1},
{ko:"시간",jp:"時間",category:"daily",level:1},
{ko:"오늘",jp:"今日",category:"daily",level:1},
{ko:"내일",jp:"明日",category:"daily",level:1},
{ko:"어제",jp:"昨日",category:"daily",level:1},
{ko:"지금",jp:"今",category:"daily",level:1},
{ko:"아침",jp:"朝",category:"daily",level:1},
{ko:"점심",jp:"昼ご飯",category:"daily",level:1},
{ko:"저녁",jp:"夕ご飯",category:"daily",level:1},
{ko:"버스",jp:"バス",category:"daily",level:1},
{ko:"병원",jp:"病院",category:"daily",level:1},
{ko:"공원",jp:"公園",category:"daily",level:1},

{ko:"좋아",jp:"好き",category:"emotion",level:2},
{ko:"싫어",jp:"嫌い",category:"emotion",level:2},
{ko:"예뻐",jp:"きれい",category:"emotion",level:2},
{ko:"귀여워",jp:"かわいい",category:"emotion",level:2},
{ko:"재밌어",jp:"面白い",category:"emotion",level:2},
{ko:"배고파",jp:"お腹すいた",category:"emotion",level:2},
{ko:"피곤해",jp:"疲れた",category:"emotion",level:2},

{ko:"어디 가?",jp:"どこ行くの？",category:"conversation",level:2},
{ko:"지금 뭐 해?",jp:"今何してる？",category:"conversation",level:2},
{ko:"밥 먹었어?",jp:"ご飯食べた？",category:"conversation",level:2},
{ko:"진짜?",jp:"本当に？",category:"conversation",level:2},
{ko:"왜?",jp:"なぜ？",category:"conversation",level:2},
{ko:"언제?",jp:"いつ？",category:"conversation",level:2},
{ko:"누구야?",jp:"誰？",category:"conversation",level:2}

];
